[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "jira"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Jira", "Productivity", "Project Management", "Cost/Freemium"] 
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-jira"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
